# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_camera.setGeometry(QtCore.QRect(10, 10, 761, 331))
        self.label_camera.setObjectName("label_camera")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(10, 550, 321, 16))
        self.label_name.setObjectName("label_name")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(10, 570, 371, 21))
        self.label_time.setObjectName("label_time")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(10, 360, 111, 28))
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(10, 400, 111, 28))
        self.btn_stop.setObjectName("btn_stop")
        self.table_log = QtWidgets.QTableWidget(self.centralwidget)
        self.table_log.setGeometry(QtCore.QRect(190, 360, 531, 241))
        self.table_log.setObjectName("table_log")
        self.table_log.setColumnCount(0)
        self.table_log.setRowCount(0)
        self.btn_kaydet = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kaydet.setGeometry(QtCore.QRect(10, 440, 151, 28))
        self.btn_kaydet.setObjectName("btn_kaydet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_camera.setText(_translate("MainWindow", "Görüntü"))
        self.label_name.setText(_translate("MainWindow", "Personel"))
        self.label_time.setText(_translate("MainWindow", "Tarih/Saat:"))
        self.btn_start.setText(_translate("MainWindow", "Başlat"))
        self.btn_stop.setText(_translate("MainWindow", "Duraklat"))
        self.btn_kaydet.setText(_translate("MainWindow", "Personel Resmi Ekle"))
